name: Periodic health check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - uses: jtalk/url-health-check-action@v5
        with:
          url: https://fs-pokedex-pd98.onrender.com/health
